### ISSUE TITLE
Special Characters in Textarea

### ISSUE THREAD

**Issue by BrianSahagun** [helgatheviking/WP-Alchemy-Holy-Grail-Theme#3]
I ran into another problem.

I copy and pasted a block of text in a list with special characters such as "Weißenburg" and "Hasenbühl".

It does not save visually all the text in that textarea if there's a special character so you see a blank textarea. But it is shown on the front-end website.

Locally it's working fine.

**Comment by helgatheviking** [comment]
Good news, this seems to be resolved... either by something that I did or by WordPress 4.3.
