### ISSUE TITLE
Line breaks not being preserved

### ISSUE THREAD

**Issue by kmh3785** [helgatheviking/WP-Alchemy-Holy-Grail-Theme#5]
As the title says, line breaks are not being preserved in the repeating text boxes, and I can't figure out why.

I have tried adding these options both alone, and in various combinations to textareas:{} tmc_settings:{}, and tmc_defaults:{}, and none of them seem to do the trick
```
remove_linebreaks: false,
convert_newlines_to_brs: true,
force_p_newlines: true
```

Any idea how to get linebreaks to be preserved when a page is updated?

Edit: I've found that the line breaks will stay preserved -if- I explicitly specify an alignment for for the block of text, then add my line breaks.

**Comment by helgatheviking** [comment]
Hi! Thanks for the ticket. I just wanted to let you know that I've received it, but I'm in the process of moving and then travelling so I won't be able to look into it until June. Unfortunately, I have no idea why line breaks wouldn't work. I haven't looked at this project in a while. 

Do you mean on the admin side? Or on the front-side? On the admin-side the settings should mimic that of the main content area. On the front-end you need to run the content through the filters for `the_content`. See [functions.php](https://github.com/helgatheviking/WP-Alchemy-Holy-Grail-Theme/blob/master/functions.php#L93-99) coupled with [content.php](https://github.com/helgatheviking/WP-Alchemy-Holy-Grail-Theme/blob/master/content.php#L66)

**Comment by kmb40** [comment]
Hi Kathy. Experiencing a similar issue. Have there been any further findings on this? Hope the move went well. Thanks,

**Comment by helgatheviking** [comment]
I completely forgot about this. That said, I just tested WP Alchemy Holy Grail theme on my local set up and linebreaks and paragraphs both seem to be maintained. By default, my code tries to pull its tinymce settings from the main post editor. So if you have a plugin/theme that has changed that somehow, or if you have a post type that doesn't support the main editor, that *might* be responsible. 

![image](https://cloud.githubusercontent.com/assets/507025/8085424/b82d7626-0f55-11e5-9738-b79f78709d76.png)

**Comment by kmb40** [comment]
Hi Kathy,

Thanks for your response. This appears to work fine in the static editor as seen below:
![screen shot 2015-06-12 at 7 31 54 am](https://cloud.githubusercontent.com/assets/1646055/8129372/a592938e-10d6-11e5-880d-112de57a1ca4.png)

However while trying to do the same thing in the repeating steps section, there seem to be some issues producing the same result. Things look good until, you switch from text to visual tabs or ice versa.
![screen shot 2015-06-12 at 7 50 31 am](https://cloud.githubusercontent.com/assets/1646055/8129512/e36a7572-10d7-11e5-8bf6-13a34b453197.png)


Thanks for your time.

**Comment by helgatheviking** [comment]
Ok, so the problem occurs on saving. I see that now locally. If I had to guess the issue is with:

```<?php echo esc_html( apply_filters( 'the_editor_content', html_entity_decode( $mb->get_the_value() ) ) ); ?>```

in `repeating-textarea.php` as the front-end actually displays the line-breaks correctly. Or it could be an issue with tinyMCE.

**Comment by helgatheviking** [comment]
This issue also seems to be resolved now, probably by something in WordPress 4.3. Please let me know if you are still having issues.
