### ISSUE TITLE
did WP 4.3 break repeating text areas?

### ISSUE THREAD

**Issue by ssuess** [helgatheviking/WP-Alchemy-Holy-Grail-Theme#6]
I have a plugin which is substantially based on this code and it no longer works in 4.3...any idea if your theme is broken and if so how to fix it? (I will download and test it separately now...)

**Comment by ssuess** [comment]
I can verify that it is also broken in your repeating textarea code on a virgin 4.3 WP system (not just in my plugin). Unfortunately there doesn't seem to be a lot of good error info, nothing useful in the console except this:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (meta.css.map, line 0)

And turning on debug in the wp-config file likewise produces no errors...

**Comment by ssuess** [comment]
could this be the cause? https://make.wordpress.org/core/2015/07/09/editor-changes-in-wordpress-4-3/

**Comment by helgatheviking** [comment]
Thank you for the report. As I mentioned in my email I will look into it when I get a chance. Please let me know if you find a solution.

**Comment by ssuess** [comment]
Well I tried changing this:


			// 'html' is used for the "Text" editor tab.
			if ( 'html' === wp_default_editor() ) {
				add_filter( 'the_editor_content', 'wp_htmledit_pre' );
				$switch_class = 'html-active';
			} else {
				add_filter( 'the_editor_content', 'wp_richedit_pre' );
				$switch_class = 'tmce-active';
			}
		

to this:


			// 'html' is used for the "Text" editor tab.
			if ( 'html' === wp_default_editor() ) {
				add_filter( 'the_editor_content', 'format_for_editor' );
				$switch_class = 'html-active';
			} else {
				add_filter( 'the_editor_content', 'format_for_editor' );
				$switch_class = 'tmce-active';
			}
			

but no dice :(

**Comment by helgatheviking** [comment]
Took a quick look and it seems like it might be an easy fix. The metabox script is not loading. I've changed the [depencies](https://github.com/helgatheviking/WP-Alchemy-Holy-Grail-Theme/blob/master/functions.php#L85) and that gets it loading. It isn't loading after the tinymce is initialized, which used to be very important, but seems to work now in spite of it. 

Would you mind testing everything out? FYI- I updated it to a twenty fifteen child theme. I presume most are rolling it into their own themes, but wanted to let you know the demo has been modified.

**Comment by ssuess** [comment]
I will check it out and report back, thanks!

**Comment by ssuess** [comment]
That seems to have fixed it, thanks!! 

Except $theme_version was not defined, so once I added that all good. And because I had wp debug on, it was also throwing an error about wp_htmledit_pre but as I reapplied my changes above to format_for_editor that also went away.

Thanks again!!

One last question: how did you track that down? I had ZERO errors showing in debug console...

**Comment by helgatheviking** [comment]
Where was `$theme_version` undefined? I'm defining it right [here](https://github.com/helgatheviking/WP-Alchemy-Holy-Grail-Theme/blob/master/functions.php#L70). Or did you mean on your version?

And yes `wp_htmledit_pre` and `wp_richedit_pre` are both deprecated... and seemingly you don't need to replace them. I have [removed them entirely](https://github.com/helgatheviking/WP-Alchemy-Holy-Grail-Theme/blob/master/metaboxes/repeating-textarea.php#L35-L39). 

I tracked it down by viewing the page source, looking for my script and seeing that it wasn't there in the markup. I've had that happen to me enough times that it is part of my debug process.

**Comment by ssuess** [comment]
Oh I had just changed the one line (instead of redownloading the whole package), so I guess that variable was not defined in the version I downloaded yesterday. Thanks again.
