### ISSUE TITLE
Multiple static textboxes, issues with scripts

### ISSUE THREAD

**Issue by photonicsLeadDev** [helgatheviking/WP-Alchemy-Holy-Grail-Theme#8]
I am trying to integrate this code into a plugin I'm writing, where I was already using WPAlchemy, but needed the multiple WYSIWYG functionality.

I'm having a few issues:

The kia-metabox script will not load with the "wp-fullscreen" script as a requirement, for whatever reason.

My custom post type does not have "editor" in the "supports" argument, because I have no need for the main content box for this post type, but the meta box editors do not seem to work without it enabled (I get this error from the kia-metabox script: Uncaught ReferenceError: tinymce is not defined).

I finally got it working after accounting for the above, using the example in "repeating-textarea.php", but when you click between the Text/Visual modes on one editor, the screen seems to jump around and focus on the other editors seemingly randomly.

I was also wondering if there was a way to have multiple STATIC editors. I have no need for the repeating fields, but I'm not entirely sure how to make more than one static editor work properly.

I hope you are able to help. Thanks for your time and work on this project!

**Comment by helgatheviking** [comment]
> My custom post type does not have "editor" in the "supports" argument

That does seem to be the case. It might be easier to just declare editor support and hide the main editor... alchemy already offers this.

Eventually, I will probably remove the fullscreen requirement, but this repo doesn't get a lot of attention from me these days since I don't use it much. However If you are using static editors, why do you need my script at all? when you call `wp_editor()` that should (in theory) load all the required scripts and handle text/visual toggling.

**Comment by photonicsLeadDev** [comment]
Ok I didn't realize that, thank you.

Well I tried that route already, and only the first editor would work and I believed your script to be the solution. Any subsequent editors I tried to include in my meta box, would have the "Text" and "Visual" tabs, but they would not function at all.

**Comment by photonicsLeadDev** [comment]
I went back to the standard WPAlchemy and got the multiple wp_editor thing working by using separate meta boxes for each one.

**Comment by helgatheviking** [comment]
You don't need multiple metaboxes if you use arrays in the `textarea_name` parameter. See [wp_editor](https://codex.wordpress.org/Function_Reference/wp_editor).
